"""init

Revision ID: 3d0a2a346b3c
Revises: 
Create Date: 2025-08-23 19:19:44.219623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3d0a2a346b3c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requesthistorymodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('browser_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_time', sa.Float(), nullable=False),
    sa.Column('response_size', sa.Integer(), nullable=False),
    sa.Column('response_headers', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('response_body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_headers', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requesthistorymodel_url'), 'requesthistorymodel', ['url'], unique=False)
    op.create_index(op.f('ix_requesthistorymodel_url_hash'), 'requesthistorymodel', ['url_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requesthistorymodel_url_hash'), table_name='requesthistorymodel')
    op.drop_index(op.f('ix_requesthistorymodel_url'), table_name='requesthistorymodel')
    op.drop_table('requesthistorymodel')
    # ### end Alembic commands ###
